### ISSUE TITLE
It is possible to set the same keys over and over again

### ISSUE THREAD

**Issue by gflarity** [indutny/node-index#4]
It is possible to set the same keys over and over again using the code provided here https://gist.github.com/891587

**Comment by indutny** [comment]
Commited: https://github.com/donnerjack13589/node-index/commit/6db425a79818290bc1ad0137ee5209c3b7f0d812

But "I see key ..." isn't a bug, function a running asynchronously so https://gist.github.com/891587#L29 here **key** variable changes.

**Comment by gflarity** [comment]
I just pulled and I can still insert the same keys over and over again using that fs-test-uuid.js? Are you sure it's fixed?
