### ISSUE TITLE
Without proper context, callbacks aren't valuable?

### ISSUE THREAD

**Issue by gflarity** [indutny/node-index#5]
See the code provided by https://gist.github.com/891587

Perhaps there is another way to do this properly that am I not understanding? Otherwise you need to include some sort of context passing mechanism. Should be easy enough and I don' t mind doing it if you're willing to pull it.

**Comment by indutny** [comment]
Dublicate.

**Comment by gflarity** [comment]
I agree. I was suggesting a new feature. It would look like:

https://gist.github.com/893239

Otherwise I'd have to do something like:

https://gist.github.com/893258

Maybe that's not so bad. It just seems like context would make things easier.

**Comment by indutny** [comment]
I think that function scope will solve that problem. This module is supposed to be behind http server (that I'll implement later), so all insertion and e.t.c. will be run from request handler, which itself has a context.
